---
- name: Set rally command according to install method for package
  set_fact:
    rally_cmd: 'source /home/rally/rally/bin/activate && rally'
  when: rally_install_method == 'package'

- name: Set rally command according to install method for container
  set_fact:
    rally_cmd: "podman run -v /home/rally/rally/etc/rally/rally.conf:/home/rally/.rally/rally.conf -v /home/rally:/home/rally/.rally {{ container_image }}"
  when: rally_install_method == 'container'

- name: Check if tempest_skip_tests is not defined
  assert:
    that: tempest_skip_tests is not defined
    msg: "Note the global tempest_skip_tests variable has now been moved to a per cloud env variable"

- name: Check existing deployments
  shell: "{{ rally_cmd }} deployment list"
  register: deployments
  changed_when: False
  args:
    executable: /bin/bash

- name: Create directories for deployments
  file: path=/home/rally/{{ item.key }} owner=rally group=rally mode=0750 state=directory
  with_dict: "{{ clouds }}"
  when: item.key not in deployments.stdout | default([])
  loop_control:
    label: "{{ item.key }}"

- name: Create deployment files
  template: src=deploy.json.j2 dest=/home/rally/{{ item.key }}/deploy.json owner=rally group=rally mode=0760
  with_dict: "{{ clouds }}"
  when: item.key not in deployments.stdout | default([])
  loop_control:
    label: "{{ item.key }}"

- name: Create deployments
  become_user: rally
  shell: "{{ rally_cmd }} deployment create --file /home/rally/{{ item.key }}/deploy.json --name {{ item.key }}"
  with_dict: "{{ clouds }}"
  when: item.key not in deployments.stdout | default([])
  args:
    executable: /bin/bash
  loop_control:
    label: "{{ item.key }}"

- name: Remove deployment directories
  file: path=/home/rally/{{ item.key }} state=absent
  with_dict: "{{ clouds }}"
  when: item.key not in deployments.stdout | default([])
  loop_control:
    label: "{{ item.key }}"

- import_tasks: tempest.yml
  when: configure_tempest

- name: Create directories for deployments
  file: path={{rally_openstack_gitrepo_dest|dirname}} owner=rally group=rally mode=0750 state=directory

- name: clone openstack/rally-openstack to get the samples directory - useful for tasks
  git: repo="{{ rally_openstack_gitrepo_source }}" dest="{{ rally_openstack_gitrepo_dest }}" version="{{ rally_openstack_gitrepo_version|default(omit) }}"
