---
- name: Check if tempest_skip_tests is not defined
  assert:
    that: tempest_skip_tests is not defined
    msg: "Note the global tempest_skip_tests variable has now been moved to a per cloud env variable"

- name: Check existing deployments
  shell: source /home/rally/rally/bin/activate && rally deployment list && deactivate
  register: deployments
  changed_when: False
  args:
    executable: /bin/bash

- name: Create directories for deployments
  file: path=/home/rally/{{ item.key }} owner=rally group=rally mode=0750 state=directory
  with_dict: "{{ clouds }}"
  when: item.key not in deployments.stdout | default([])
  no_log: True

- name: Create deployment files
  template: src=deploy.json.j2 dest=/home/rally/{{ item.key }}/deploy.json owner=rally group=rally mode=0760
  with_dict: "{{ clouds }}"
  when: item.key not in deployments.stdout | default([])
  no_log: True

- name: Create deployments
  become_user: rally
  shell: source /home/rally/rally/bin/activate && rally deployment create --file /home/rally/{{ item.key }}/deploy.json --name {{ item.key }} && deactivate
  with_dict: "{{ clouds }}"
  when: item.key not in deployments.stdout | default([])
  no_log: True
  args:
    executable: /bin/bash

- name: Remove deployment directories
  file: path=/home/rally/{{ item.key }} state=absent
  with_dict: "{{ clouds }}"
  when: item.key not in deployments.stdout | default([])
  no_log: True

- import_tasks: tempest.yml
  when: configure_tempest
