---
- name: Get image
  become: false
  get_url:
    url: "{{ img_url }}"
    dest: "/tmp/{{ img_url | basename }}"
    timeout: 30

- name: Install qemu-img
  package:
    name: qemu-img

- name: Convert image to raw format
  become: false
  command:
    cmd: "qemu-img convert -f qcow2 -O raw /tmp/{{ img_url | basename }} /tmp/{{ img_url | basename }}.raw"

- include_tasks: tempest_verifiers.yml
  with_dict: "{{ clouds }}"
