---

- name: "We are now configuring {{ item.key }}"
  debug:
    msg: "We are now configuring {{ item.key }}"

- name: Select scenario {{ item.key }}
  become_user: "{{ rally_user }}"
  shell: "{{ rally_cmd }} deployment use {{ item.key }}"
  changed_when: False
  args:
    executable: /bin/bash

- name: Check existing rally verifiers
  become_user: "{{ rally_user }}"
  shell: "{{ rally_cmd }} verify list-verifiers | grep -v WARNING"
  register: verifiers
  changed_when: False
  args:
    executable: /bin/bash

- name: Create rally verifiers
  become_user: "{{ rally_user }}"
  shell: "{{ rally_cmd }} deployment use {{ item.key }} &>/dev/null && {{ rally_cmd }} verify create-verifier --type tempest --name {{ item.key }} --source {{ tempest_source }} --version {{ tempest_version }} "
  when: item.key not in verifiers.stdout | default([])
  register: verifier_created
  args:
    executable: /bin/bash

- block:
  - name: Check for image
    shell: "{{ rally_cmd }} deployment use {{ item.key }} &>/dev/null && source /home/rally/.rally/openrc && {{ openstack_cmd }} openstack image list --public -f value -c Name |grep {{ img_name }}$"
    register: existing_images
    failed_when: existing_images.rc  > 1
    changed_when: False
    args:
      executable: /bin/bash

  - name: Upload image to openstack
    shell: "{{ rally_cmd }} deployment use {{ item.key }} &>/dev/null && source /home/rally/.rally/openrc && {{ openstack_cmd }} glance image-create --name {{ img_name }} --visibility public --file /tmp/{{ img_url | basename }}.raw --container-format bare --disk-format raw"
    when: existing_images.rc == 1
    args:
      executable: /bin/bash

  - name: Get image id
    shell: "{{ rally_cmd }} deployment use {{ item.key }} &>/dev/null && source /home/rally/.rally/openrc && {{ openstack_cmd }} openstack image list --public -f value -c Name -c ID | grep {{ img_name }}$ | cut -f 1 -d ' ' | head -n 1"
    register: image_id
    changed_when: False
    args:
      executable: /bin/bash

  - name: Check for test flavor
    shell: "{{ rally_cmd }} deployment use {{ item.key }} &>/dev/null && source /home/rally/.rally/openrc && {{ openstack_cmd }} nova flavor-list  |grep {{ tempest_test_flavor }} | cut -f 2 -d  '|' | head -n 1"
    register: flavor_id
    changed_when: False
    args:
      executable: /bin/bash

  - name: Check for second test flavor
    shell: "{{ rally_cmd }} deployment use {{ item.key }} &>/dev/null && source /home/rally/.rally/openrc && {{ openstack_cmd }} nova flavor-list  |grep {{ tempest_second_test_flavor }} | cut -f 2 -d  '|' | head -n 1"
    register: second_flavor_id
    changed_when: False
    args:
      executable: /bin/bash

  - name: Check for public network UUID
    shell: "{{ rally_cmd }} deployment use {{ item.key }} &>/dev/null && source /home/rally/.rally/openrc && {{ openstack_cmd }} openstack network list --external |grep public |  cut -f 2 -d  '|' | head -n 1"
    register: public_network_id
    changed_when: False
    args:
      executable: /bin/bash

  - name: Set ansible facts used in tempest config
    set_fact:
      tempest_image_uuid: "{{ image_id.stdout }}"
      tempest_flavor_uuid: "{{ flavor_id.stdout }}"
      tempest_second_flavor_uuid: "{{ second_flavor_id.stdout }}"
      tempest_network_name: "{{ item.value.network_name }}"
      tempest_public_network_id: "{{ public_network_id.stdout }}"

  - name: store tempest configs in a persistent place
    file:
      state: directory
      path: /home/rally/tempest_configs
      mode: 0700
      owner: rally
      group: rally

  - name: Template in tempest config
    template: src=tempest.j2 dest=/home/rally/tempest_configs/{{ item.key }}.tempest owner=rally group=rally mode=0700
    register: reg_tempest_config

  - name: Configure rally verifier if templating in the templest config file task changed or new verifier created
    shell: "{{ rally_cmd }} deployment use {{ item.key }} &>/dev/null && {{ rally_cmd }} verify use-verifier --id {{ item.key }} &&  {{ rally_cmd }} verify configure-verifier --extend /home/rally/tempest_configs/{{ item.key }}.tempest"
    args:
      executable: /bin/bash
    when: reg_tempest_config.changed or verifier_created is not skipped

  - name: Template in skip list
    template: src=tempest_skip_list.yml.j2 dest={{ deployments_folder }}/{{ item.key }}-skip-list.yml owner=rally group=rally mode=0600

  - name: Template in tempest run bash script
    template: src=tempest_run.sh.j2 dest={{ deployments_folder }}/{{ item.key }}-tempest_run.sh owner=rally group=rally mode=0700

  # - name: "Configure cronjob for deployment {{ item.key }}"
  #   cron:
  #     name: "Run tempest against {{ item.key }}"
  #     user: "{{ rally_user }}"
  #     hour: "{{ item.value.tempest_cron_run_hour }}"
  #     minute: "0"
  #     job: "{{ deployments_folder }}/{{ item.key }}-tempest_run.sh --tag cron_$(date +%Y_%m_%d_%H)"
  #   when: item.value.configure_tempest_cron | default('false')

  - name: Create systemd service unit
    template:
      src: tempest_run.service.j2
      dest: /etc/systemd/system/tempest_run_{{ item.key }}.service
      mode: 0600
    when: item.value.configure_tempest_cron | default('false')

  - name: Enable tempest run service
    systemd:
      name: "tempest_run_{{ item.key }}.service"
      enabled: true
      masked: false
      daemon_reload: true

  - name: Create systemd timer unit
    template:
      src: tempest_run.timer.j2
      dest: /etc/systemd/system/tempest_run_{{ item.key }}.timer
      mode: 0600
    when: item.value.configure_tempest_cron | default('false')

  - name: Enable tempest run timer
    systemd:
      name: "tempest_run_{{ item.key }}.timer"
      enabled: true
      masked: false
      daemon_reload: true

  become_user: "{{ rally_user }}"
  environment:
    ftp_proxy: ""
    http_proxy: ""
    https_proxy: ""
