---
- name: Get image locally
  become: false
  local_action:
    module: get_url
    url: "{{ rally_cirros_img_url}}/{{ rally_cirros_img_name }}"
    dest: "/tmp/{{ rally_cirros_img_name }}"
    use_proxy: no

- name: Convert image to raw format
  become: false
  local_action:
    module: command
    cmd: "qemu-img convert -f qcow2 -O raw /tmp/{{ rally_cirros_img_name }} /tmp/{{ rally_cirros_img_name }}.raw"

- name: Upload image to rally server
  copy:
    src: "/tmp/{{ rally_cirros_img_name }}.raw"
    dest: "/tmp/{{ rally_cirros_img_name }}.raw"
    owner: root
    group: root
    mode: '0644'

- include_tasks: tempest_verifiers.yml
  with_dict: "{{ clouds }}"
